repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: pretty-format-json
    args: [--autofix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.7
  hooks:
    # Run the linter.
  - id: ruff
    types_or: [python, pyi, jupyter]
    args: [--fix, --show-fixes]
    # Run the formatter.
  - id: ruff-format
    types_or: [python, pyi, jupyter]
