site_name: gopher
repo_url: https://github.com/TalusBio/gopher
nav:
  - Home: index.md
  - API: api.md
  - Examples: examples.md
  - Vignette: vignettes.ipynb

theme:
  name: material
  favicon: static/talus-logo.svg
  logo: static/talus-logo.svg
  font:
    text: IBM Plex Sans
  features:
     - toc.integrate
     - navigation.tabs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.arithmatex

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/talusbio

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            heading_level: 3
            docstring_section_style: spacy
            show_source: false
            merge_init_into_class: true
          inventories:
            - https://seaborn.pydata.org/objects.inv
  - mkdocs-jupyter
