name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black[colorama]==24.10.0

      - name: Run black
        uses: psf/black@stable

      - name: Check for debugging print statements
        run: |
          if grep -rq "print(" gopher; then
              echo "Found the following print statements:"
              grep -r "print(" gopher
              exit 1
          fi
